sudo: true 
cache: pip 
python: "3.7" 
language: python

# only execute if the main branch has changed (from a merge)
if: type = push AND branch = main

install: # install dependencies (cached)
  - pip install -r requirements.txt

script:
  - ./build -c # run clean build
  - mv docs/ gh-pages/

deploy:
  provider: pages # github pages provider
  on: 
    branch:
      - main
  skip_cleanup: true # save the build output (artifact)
  local_dir: gh-pages # the directory to deploy to GH pages
  target_branch: gh-pages # branch to push the build artifact to 
  github_token: $GITHUB_ACCESS_TOKEN # access token with repo:public scope