name: Deploy Master on Merge

on:
  push:
    branches:    
      - main

jobs:
  build:
    name: Install, Build, Deliver
    runs-on: ubuntu-latest

    steps:
    - name: Check out Repository Code
    - uses: actions/checkout@master

    - name: Build Sphinx
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs"
        build-command: "sphinx-build src docs"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.TOKEN }}
