name: "Deploy Master on Merge"
on:
  push:
    branches:
      - main 

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: ammaraskar/sphinx-action@master
      with:
        build-command: "sphinx-build src docs"
        docs-folder: "docs/"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.TOKEN }}
